### ISSUE TITLE
Why boosting the repo with bots?

### ISSUE THREAD

**Issue by nskazki** [jorisperrenet/durak_bots#1]
I mean no disrespect, and asking out of pure curiosity, why are you boosting this repo with bots?

- https://github.com/collisonemmanuel736
- https://github.com/dennisdecker578
- https://github.com/reillystone28

**Comment by jorisperrenet** [comment]
As a dull prank. Shortly, I will renew this repo as to remove the unjust stars.

**Comment by jorisperrenet** [comment]
The non-boosted version of this repo can be found at [https://github.com/jorisperrenet/durak](https://github.com/jorisperrenet/durak).
